// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {models} from '../models';
import {service} from '../models';

export function ClearGlobalProxy():Promise<void>;

export function ClearSessions(arg1:string):Promise<void>;

export function CreateMcpServer(arg1:app.CreateMcpServerRequest):Promise<models.McpServer>;

export function CreateProfile(arg1:app.CreateProfileRequest):Promise<models.Profile>;

export function CreateProvider(arg1:app.CreateProviderRequest):Promise<models.Provider>;

export function CreateProxy(arg1:app.CreateProxyRequest):Promise<models.Proxy>;

export function CreateSkill(arg1:app.CreateSkillRequest):Promise<models.Skill>;

export function DeleteMcpServer(arg1:number):Promise<void>;

export function DeleteProfile(arg1:number):Promise<void>;

export function DeleteProvider(arg1:number):Promise<void>;

export function DeleteProxy(arg1:number):Promise<void>;

export function DeleteSession(arg1:number):Promise<void>;

export function DeleteSetting(arg1:string):Promise<void>;

export function DeleteSkill(arg1:number):Promise<void>;

export function DetectCliTool(arg1:string):Promise<service.DetectResult>;

export function FetchProviderModels(arg1:number):Promise<Array<string>>;

export function GetAllSettings():Promise<Record<string, string>>;

export function GetCliSessionMessages(arg1:string,arg2:string):Promise<Array<service.CliSessionMessage>>;

export function GetCliSessionProjects(arg1:string):Promise<Array<service.CliSessionProject>>;

export function GetCliSessions(arg1:app.GetCliSessionsRequest):Promise<Array<service.CliSession>>;

export function GetCliToolActiveConfig(arg1:string):Promise<service.ActiveConfig>;

export function GetCliToolMcpServers(arg1:string):Promise<Array<models.McpServer>>;

export function GetCliTools():Promise<Array<models.CliTool>>;

export function GetMcpServers():Promise<Array<models.McpServer>>;

export function GetProfiles():Promise<Array<models.Profile>>;

export function GetProviders():Promise<Array<models.Provider>>;

export function GetProxies():Promise<Array<models.Proxy>>;

export function GetSessions(arg1:app.GetSessionsRequest):Promise<Array<models.Session>>;

export function GetSetting(arg1:string,arg2:string):Promise<string>;

export function GetSkills():Promise<Array<models.Skill>>;

export function LaunchCliTool(arg1:app.LaunchRequest):Promise<void>;

export function ListAvailableTerminals():Promise<Array<service.TerminalInfo>>;

export function RelaunchSession(arg1:number):Promise<void>;

export function SetCliToolActiveConfig(arg1:app.SetActiveConfigRequest):Promise<void>;

export function SetCliToolMcpServers(arg1:string,arg2:Array<number>):Promise<void>;

export function SetGlobalProxy(arg1:number):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function TestProvider(arg1:number):Promise<service.TestResult>;

export function UpdateMcpServer(arg1:number,arg2:app.UpdateMcpServerRequest):Promise<void>;

export function UpdateProfile(arg1:number,arg2:app.UpdateProfileRequest):Promise<void>;

export function UpdateProvider(arg1:number,arg2:app.UpdateProviderRequest):Promise<void>;

export function UpdateProxy(arg1:number,arg2:app.UpdateProxyRequest):Promise<void>;

export function UpdateSkill(arg1:number,arg2:app.UpdateSkillRequest):Promise<void>;
