// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearGlobalProxy() {
  return window['go']['app']['App']['ClearGlobalProxy']();
}

export function ClearSessions(arg1) {
  return window['go']['app']['App']['ClearSessions'](arg1);
}

export function CreateMcpServer(arg1) {
  return window['go']['app']['App']['CreateMcpServer'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['app']['App']['CreateProfile'](arg1);
}

export function CreateProvider(arg1) {
  return window['go']['app']['App']['CreateProvider'](arg1);
}

export function CreateProxy(arg1) {
  return window['go']['app']['App']['CreateProxy'](arg1);
}

export function CreateSkill(arg1) {
  return window['go']['app']['App']['CreateSkill'](arg1);
}

export function DeleteMcpServer(arg1) {
  return window['go']['app']['App']['DeleteMcpServer'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['app']['App']['DeleteProfile'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['app']['App']['DeleteProvider'](arg1);
}

export function DeleteProxy(arg1) {
  return window['go']['app']['App']['DeleteProxy'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['app']['App']['DeleteSession'](arg1);
}

export function DeleteSetting(arg1) {
  return window['go']['app']['App']['DeleteSetting'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['app']['App']['DeleteSkill'](arg1);
}

export function DetectCliTool(arg1) {
  return window['go']['app']['App']['DetectCliTool'](arg1);
}

export function FetchProviderModels(arg1) {
  return window['go']['app']['App']['FetchProviderModels'](arg1);
}

export function GetAllSettings() {
  return window['go']['app']['App']['GetAllSettings']();
}

export function GetCliSessionMessages(arg1, arg2) {
  return window['go']['app']['App']['GetCliSessionMessages'](arg1, arg2);
}

export function GetCliSessionProjects(arg1) {
  return window['go']['app']['App']['GetCliSessionProjects'](arg1);
}

export function GetCliSessions(arg1) {
  return window['go']['app']['App']['GetCliSessions'](arg1);
}

export function GetCliToolActiveConfig(arg1) {
  return window['go']['app']['App']['GetCliToolActiveConfig'](arg1);
}

export function GetCliToolMcpServers(arg1) {
  return window['go']['app']['App']['GetCliToolMcpServers'](arg1);
}

export function GetCliTools() {
  return window['go']['app']['App']['GetCliTools']();
}

export function GetMcpServers() {
  return window['go']['app']['App']['GetMcpServers']();
}

export function GetProfiles() {
  return window['go']['app']['App']['GetProfiles']();
}

export function GetProviders() {
  return window['go']['app']['App']['GetProviders']();
}

export function GetProxies() {
  return window['go']['app']['App']['GetProxies']();
}

export function GetSessions(arg1) {
  return window['go']['app']['App']['GetSessions'](arg1);
}

export function GetSetting(arg1, arg2) {
  return window['go']['app']['App']['GetSetting'](arg1, arg2);
}

export function GetSkills() {
  return window['go']['app']['App']['GetSkills']();
}

export function LaunchCliTool(arg1) {
  return window['go']['app']['App']['LaunchCliTool'](arg1);
}

export function ListAvailableTerminals() {
  return window['go']['app']['App']['ListAvailableTerminals']();
}

export function RelaunchSession(arg1) {
  return window['go']['app']['App']['RelaunchSession'](arg1);
}

export function SetCliToolActiveConfig(arg1) {
  return window['go']['app']['App']['SetCliToolActiveConfig'](arg1);
}

export function SetCliToolMcpServers(arg1, arg2) {
  return window['go']['app']['App']['SetCliToolMcpServers'](arg1, arg2);
}

export function SetGlobalProxy(arg1) {
  return window['go']['app']['App']['SetGlobalProxy'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['app']['App']['SetSetting'](arg1, arg2);
}

export function TestProvider(arg1) {
  return window['go']['app']['App']['TestProvider'](arg1);
}

export function UpdateMcpServer(arg1, arg2) {
  return window['go']['app']['App']['UpdateMcpServer'](arg1, arg2);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['app']['App']['UpdateProfile'](arg1, arg2);
}

export function UpdateProvider(arg1, arg2) {
  return window['go']['app']['App']['UpdateProvider'](arg1, arg2);
}

export function UpdateProxy(arg1, arg2) {
  return window['go']['app']['App']['UpdateProxy'](arg1, arg2);
}

export function UpdateSkill(arg1, arg2) {
  return window['go']['app']['App']['UpdateSkill'](arg1, arg2);
}
